version: '2'

services:

  postgres:
    image: postgres:12
    restart: always
    ports:
      - "7011:5432"
    environment:
      POSTGRES_DB: mars
      POSTGRES_USER: i_use_mars
      POSTGRES_PASSWORD: 111
